apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nataliagranato
  region: us-east-1
  version: "1.29"

managedNodeGroups:
- name: ng-ondemand
  instanceTypes: ["m6a.xlarge"]
  spot: false
  privateNetworking: true
  minSize: 1
  maxSize: 1
  desiredCapacity: 1
  volumeSize: 50
  volumeType: gp3
  updateConfig:
    maxUnavailablePercentage: 30
  availabilityZones: ["us-east-1a"]
  ssh:
    allow: false
  labels:
    node_group: ng-ondemand
  tags:
    nodegroup-role: ng-ondemand
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/nataliagranato: "owned"
    nataliagranato.vercel.app: "true"

  iam:
    withAddonPolicies:
      externalDNS: true
      certManager: true
      imageBuilder: true
      albIngress: true
      autoScaler: true
      ebs: true
      efs: true
