apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: nataliagranato
  region: us-east-1
  version: "1.29"


managedNodeGroups:
- name: ng-spot
  instanceTypes: ["m6a.xlarge", "m6i.xlarge", "c6in.2xlarge", "m5a.xlarge", "c6in.2xlarge", "c5.2xlarge", "c6a.2xlarge"]
  spot: true
  privateNetworking: true
  minSize: 1
  maxSize: 5
  desiredCapacity: 3
  volumeSize: 50
  volumeType: gp3
  updateConfig:
    maxUnavailablePercentage: 30
  availabilityZones: ["us-east-1a"]
  ssh:
    allow: false
  labels:
    node_group: ng-spot
  tags:
    nodegroup-role: ng-spot
    k8s.io/cluster-autoscaler/enabled: "true"
    k8s.io/cluster-autoscaler/nataliagranato: "owned"
    nataliagranato.vercel.app: "true"

  iam:
    withAddonPolicies:
      externalDNS: true
      certManager: true
      imageBuilder: true
      albIngress: true
      autoScaler: true
      ebs: true
      efs: true
